name = "BehavioralSystems"
uuid = "1f86e1d0-07f4-4cdc-aa25-7c52218f1bad"
authors = ["Cédric Simal", "University of Namur"]
version = "0.1.0"

[deps]
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
Lasso = "b4fcebef-c861-5a0f-a7e2-ba9dc32b180a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ControlSystemsBase = "1"
Optimization = "3"
Lasso = "0.7.0"
julia = "1"

[extras]
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "ControlSystemsBase"]
